#!/usr/bin/env python3

import sys, getopt

from prettyprint import *
from fetcht_core import *
from fetcht_gui import *

__program_name__ = "fetcht"
__version__ = '0.4'

def load_cmd(core, cmd):
    print_info("Loading command prompt");
    prompt = True if cmd in ["",[]] else False

    while core.status:
        if prompt:
            raw = input("> ")
            cmd = raw.split(" ")
        else:
            core.status = False

        core.process_command(cmd)

def usage(): # prettytable
    print_info("""Usage:\n
    --help    -h : you already know this one.
    --silent  -s  : verbosity off
    --gui     -g : load gui
    --cmd     -c : load command prompt\n
    if none of the above is specified it will try to execute arglist to the database prompt
    """)

def main():
    print_info("{0} v{1} (hex0var) GPLv2\n".format(__program_name__, __version__));

    core = fetcht_core();

    try:
        opts, args = getopt.getopt(sys.argv[1:], "hsgc", ["help","silent", "gui", "cmd"])
    except getopt.GetoptError as err:
        print_err(err)
        sys.exit(2)

    verbose = True
    parsed = False
    for o, param in opts:
        parsed = True
        if o in ("-s", "--silent"):
            verbose = False
        elif o in ("-h", "--help"):
            usage()
        elif o in ("-g", "--gui"):
            load_gui(core)
        elif o in ("-c", "--cmd"):
            load_cmd(core, "")

    if not parsed:
        load_cmd(core, sys.argv[1:])

    core.close();

if __name__ == '__main__':
    main();
